# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleWusnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ReceivedTime')),
                ('date_time_sensor', models.DateTimeField(verbose_name='DateTimeSensor')),
                ('packet_number', models.IntegerField(verbose_name='PacketNumber')),
                ('node_id', models.IntegerField(verbose_name='NodeId')),
                ('water_raw', models.IntegerField(verbose_name='WaterRaw')),
                ('water', models.IntegerField(verbose_name='Water')),
                ('temperature_raw', models.IntegerField(verbose_name='TemperatureRaw')),
                ('temperature', models.IntegerField(verbose_name='Temperature')),
                ('rssi', models.IntegerField(verbose_name='RSSI')),
                ('success_ind', models.IntegerField(verbose_name='SuccessIndicator')),
                ('checksum', models.IntegerField(verbose_name='Checksum')),
            ],
        ),
    ]
