# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleLogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplewusndata',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='simplewusndata',
            name='water',
            field=models.FloatField(verbose_name='Water'),
        ),
    ]
